CREATE TABLE "alias" (
  "db_id"            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id"               BIGINT               NOT NULL,
  "account_id"       BIGINT               NOT NULL,
  "alias_name"       VARCHAR(100) CHARACTER SET UTF8 NOT NULL,
  "alias_name_lower" VARCHAR(100) CHARACTER SET UTF8 NOT NULL,
  "alias_uri"        BLOB SUB_TYPE TEXT NOT NULL,
  "timestamp"        INT                  NOT NULL,
  "height"           INT                  NOT NULL,
  "latest"           BOOLEAN DEFAULT TRUE NOT NULL,
  UNIQUE ("id", "height")
);

CREATE TRIGGER lower_alias_name
  FOR "alias" ACTIVE BEFORE INSERT OR UPDATE POSITION 10 AS BEGIN
NEW."alias_name_lower" = LOWER ( NEW."alias_name");
END
;

CREATE UNIQUE DESCENDING INDEX "alias_id_height_idx" ON "alias"("id", "height");

CREATE DESCENDING INDEX "alias_account_id_idx" ON "alias"("account_id", "height");

CREATE INDEX "alias_name_lower_idx"
  ON "alias" ("alias_name_lower");

CREATE TABLE "account" (
  "db_id"               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id"                  BIGINT               NOT NULL,
  "creation_height"     INT                  NOT NULL,
  "public_key"          CHAR(32),
  "key_height"          INT,
  "balance"             BIGINT               NOT NULL,
  "unconfirmed_balance" BIGINT               NOT NULL,
  "forged_balance"      BIGINT               NOT NULL,
  "name"                VARCHAR(100) CHARACTER SET UTF8,
  "description"         BLOB SUB_TYPE TEXT,
  "height"              INT                  NOT NULL,
  "latest"              BOOLEAN DEFAULT TRUE NOT NULL,
  UNIQUE ("id", "height")
);

CREATE UNIQUE DESCENDING INDEX "account_id_height_idx" ON "account"("id", "height");

CREATE DESCENDING INDEX "account_id_balance_height_idx" ON "account"("id", "balance", "height");

CREATE TABLE "alias_offer" (
  "db_id"    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id"       BIGINT               NOT NULL,
  "price"    BIGINT               NOT NULL,
  "buyer_id" BIGINT,
  "height"   INT                  NOT NULL,
  "latest"   BOOLEAN DEFAULT TRUE NOT NULL,
  UNIQUE ("id", "height")
);

CREATE UNIQUE DESCENDING INDEX "alias_offer_id_height_idx" ON "alias_offer"("id", "height");

CREATE TABLE "peer" (
  "address" VARCHAR(100) PRIMARY KEY NOT NULL
);

CREATE TABLE "transaction" (
  "db_id"                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id"                          BIGINT                NOT NULL,
  "deadline"                    SMALLINT              NOT NULL,
  "sender_public_key"           CHAR(32)              NOT NULL,
  "recipient_id"                BIGINT,
  "amount"                      BIGINT                NOT NULL,
  "fee"                         BIGINT                NOT NULL,
  "height"                      INT                   NOT NULL,
  "block_id"                    BIGINT                NOT NULL,
  "signature"                   CHAR(64),
  "timestamp"                   INT                   NOT NULL,
  "type"                        SMALLINT              NOT NULL,
  "subtype"                     SMALLINT              NOT NULL,
  "sender_id"                   BIGINT                NOT NULL,
  "block_timestamp"             INT                   NOT NULL,
  "full_hash"                   CHAR(32)              NOT NULL,
  "r_t_f_hash"                  CHAR(32),
  "attachment_bytes"            BLOB,
  "version"                     SMALLINT              NOT NULL,
  "has_message"                 BOOLEAN DEFAULT FALSE NOT NULL,
  "has_encrypted_message"       BOOLEAN DEFAULT FALSE NOT NULL,
  "has_public_key_announcement" BOOLEAN DEFAULT FALSE NOT NULL,
  "ec_block_height"             INT    DEFAULT NULL,
  "ec_block_id"                 BIGINT DEFAULT NULL,
  "has_encrypttoself_message"   BOOLEAN DEFAULT FALSE NOT NULL,
  UNIQUE ("id"),
  UNIQUE ("full_hash")
);

CREATE DESCENDING INDEX "transaction_block_timestamp_idx" ON "transaction"("block_timestamp");

CREATE UNIQUE INDEX "transaction_id_idx"
  ON "transaction" ("id");

CREATE INDEX "transaction_sender_id_idx"
  ON "transaction" ("sender_id");

CREATE UNIQUE INDEX "transaction_full_hash_idx"
  ON "transaction" ("full_hash");

CREATE INDEX "transaction_recipient_id_idx"
  ON "transaction" ("recipient_id");

CREATE INDEX "t_r_i_a_h_idx"
  ON "transaction" ("recipient_id", "amount", "height");

CREATE TABLE "asset" (
  "db_id"       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id"          BIGINT      NOT NULL,
  "account_id"  BIGINT      NOT NULL,
  "name"        VARCHAR(10) NOT NULL,
  "description" BLOB SUB_TYPE TEXT,
  "quantity"    BIGINT      NOT NULL,
  "decimals"    SMALLINT    NOT NULL,
  "height"      INT         NOT NULL,
  UNIQUE ("id")
);

CREATE UNIQUE INDEX "asset_id_idx"
  ON "asset" ("id");

CREATE INDEX "asset_account_id_idx"
  ON "asset" ("account_id");

CREATE TABLE "trade" (
  "db_id"            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "asset_id"         BIGINT NOT NULL,
  "block_id"         BIGINT NOT NULL,
  "ask_order_id"     BIGINT NOT NULL,
  "bid_order_id"     BIGINT NOT NULL,
  "ask_order_height" INT    NOT NULL,
  "bid_order_height" INT    NOT NULL,
  "seller_id"        BIGINT NOT NULL,
  "buyer_id"         BIGINT NOT NULL,
  "quantity"         BIGINT NOT NULL,
  "price"            BIGINT NOT NULL,
  "timestamp"        INT    NOT NULL,
  "height"           INT    NOT NULL,
  UNIQUE ("ask_order_id", "bid_order_id")
);

CREATE UNIQUE INDEX "trade_ask_bid_idx"
  ON "trade" ("ask_order_id", "bid_order_id");

CREATE DESCENDING INDEX "trade_asset_id_idx" ON "trade"("asset_id", "height");

CREATE DESCENDING INDEX "trade_seller_id_idx" ON "trade"("seller_id", "height");

CREATE DESCENDING INDEX "trade_buyer_id_idx" ON "trade"("buyer_id", "height");

CREATE TABLE "ask_order" (
  "db_id"           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id"              BIGINT               NOT NULL,
  "account_id"      BIGINT               NOT NULL,
  "asset_id"        BIGINT               NOT NULL,
  "price"           BIGINT               NOT NULL,
  "quantity"        BIGINT               NOT NULL,
  "creation_height" INT                  NOT NULL,
  "height"          INT                  NOT NULL,
  "latest"          BOOLEAN DEFAULT TRUE NOT NULL,
  UNIQUE ("id", "height")
);

CREATE UNIQUE DESCENDING INDEX "ask_order_id_height_idx" ON "ask_order"("id", "height");

CREATE DESCENDING INDEX "ask_order_account_id_idx" ON "ask_order"("account_id", "height");

CREATE INDEX "ask_order_asset_id_price_idx"
  ON "ask_order" ("asset_id", "price");

CREATE DESCENDING INDEX "ask_order_creation_idx" ON "ask_order"("creation_height");

CREATE TABLE "bid_order" (
  "db_id"           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id"              BIGINT               NOT NULL,
  "account_id"      BIGINT               NOT NULL,
  "asset_id"        BIGINT               NOT NULL,
  "price"           BIGINT               NOT NULL,
  "quantity"        BIGINT               NOT NULL,
  "creation_height" INT                  NOT NULL,
  "height"          INT                  NOT NULL,
  "latest"          BOOLEAN DEFAULT TRUE NOT NULL,
  UNIQUE ("id", "height")
);

CREATE UNIQUE DESCENDING INDEX "bid_order_id_height_idx" ON "bid_order"("id", "height");

CREATE DESCENDING INDEX "bid_order_account_id_idx" ON "bid_order"("account_id", "height");

CREATE DESCENDING INDEX "bid_order_asset_id_price_idx" ON "bid_order"("asset_id", "price");

CREATE DESCENDING INDEX "bid_order_creation_idx" ON "bid_order"("creation_height");

CREATE TABLE "goods" (
  "db_id"       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id"          BIGINT               NOT NULL,
  "seller_id"   BIGINT               NOT NULL,
  "name"        VARCHAR(100)         NOT NULL,
  "description" BLOB SUB_TYPE TEXT,
  "tags"        VARCHAR(100),
  "timestamp"   INT                  NOT NULL,
  "quantity"    INT                  NOT NULL,
  "price"       BIGINT               NOT NULL,
  "delisted"    BOOLEAN              NOT NULL,
  "height"      INT                  NOT NULL,
  "latest"      BOOLEAN DEFAULT TRUE NOT NULL,
  UNIQUE ("id", "height")
);

CREATE UNIQUE DESCENDING INDEX "goods_id_height_idx" ON "goods"("id", "height");

CREATE INDEX "goods_seller_id_name_idx"
  ON "goods" ("seller_id", "name");

CREATE DESCENDING INDEX "goods_timestamp_idx" ON "goods"("timestamp", "height");

CREATE TABLE "purchase" (
  "db_id"                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id"                   BIGINT                NOT NULL,
  "buyer_id"             BIGINT                NOT NULL,
  "goods_id"             BIGINT                NOT NULL,
  "seller_id"            BIGINT                NOT NULL,
  "quantity"             INT                   NOT NULL,
  "price"                BIGINT                NOT NULL,
  "deadline"             INT                   NOT NULL,
  "note"                 BLOB,
  "nonce"                CHAR(32),
  "timestamp"            INT                   NOT NULL,
  "pending"              BOOLEAN               NOT NULL,
  "goods"                BLOB,
  "goods_nonce"          CHAR(32),
  "refund_note"          BLOB,
  "refund_nonce"         CHAR(32),
  "has_feedback_notes"   BOOLEAN DEFAULT FALSE NOT NULL,
  "has_public_feedbacks" BOOLEAN DEFAULT FALSE NOT NULL,
  "discount"             BIGINT                NOT NULL,
  "refund"               BIGINT                NOT NULL,
  "height"               INT                   NOT NULL,
  "latest"               BOOLEAN DEFAULT TRUE  NOT NULL,
  UNIQUE ("id", "height")
);

CREATE UNIQUE DESCENDING INDEX "purchase_id_height_idx" ON "purchase"("id", "height");

CREATE DESCENDING INDEX "purchase_buyer_id_height_idx" ON "purchase"("buyer_id", "height");

CREATE DESCENDING INDEX "purchase_seller_id_height_idx" ON "purchase"("seller_id", "height");

CREATE DESCENDING INDEX "purchase_deadline_idx" ON "purchase"("deadline", "height");

CREATE DESCENDING INDEX "purchase_timestamp_idx" ON "purchase"("timestamp", "id");

CREATE TABLE "account_asset" (
  "db_id"                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "account_id"           BIGINT               NOT NULL,
  "asset_id"             BIGINT               NOT NULL,
  "quantity"             BIGINT               NOT NULL,
  "unconfirmed_quantity" BIGINT               NOT NULL,
  "height"               INT                  NOT NULL,
  "latest"               BOOLEAN DEFAULT TRUE NOT NULL,
  UNIQUE ("account_id", "asset_id", "height")
);

CREATE UNIQUE DESCENDING INDEX "account_asset_id_height_idx" ON "account_asset"("account_id", "asset_id", "height");

CREATE DESCENDING INDEX "account_asset_quantity_idx" ON "account_asset"("quantity");

CREATE TABLE "purchase_feedback" (
  "db_id"          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id"             BIGINT               NOT NULL,
  "feedback_data"  BLOB                 NOT NULL,
  "feedback_nonce" CHAR(32)             NOT NULL,
  "height"         INT                  NOT NULL,
  "latest"         BOOLEAN DEFAULT TRUE NOT NULL
);

CREATE DESCENDING INDEX "p_f_i_h_idx" ON "purchase_feedback"("id", "height");

CREATE TABLE "purchase_public_feedback" (
  "db_id"           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id"              BIGINT               NOT NULL,
  "public_feedback" BLOB SUB_TYPE TEXT NOT NULL,
  "height"          INT                  NOT NULL,
  "latest"          BOOLEAN DEFAULT TRUE NOT NULL
);

CREATE DESCENDING INDEX "p_p_f_i_h_idx" ON "purchase_public_feedback"("id", "height");

CREATE TABLE "unconfirmed_transaction" (
  "db_id"              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id"                 BIGINT NOT NULL,
  "expiration"         INT    NOT NULL,
  "transaction_height" INT    NOT NULL,
  "fee_per_byte"       BIGINT NOT NULL,
  "timestamp"          INT    NOT NULL,
  "transaction_bytes"  BLOB   NOT NULL,
  "height"             INT    NOT NULL,
  UNIQUE ("id")
);

CREATE UNIQUE INDEX "u_t_i_idx"
  ON "unconfirmed_transaction" ("id");

CREATE DESCENDING INDEX "u_t_f_t_idx" ON "unconfirmed_transaction"("transaction_height", "fee_per_byte", "timestamp");

CREATE TABLE "asset_transfer" (
  "db_id"        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id"           BIGINT NOT NULL,
  "asset_id"     BIGINT NOT NULL,
  "sender_id"    BIGINT NOT NULL,
  "recipient_id" BIGINT NOT NULL,
  "quantity"     BIGINT NOT NULL,
  "timestamp"    INT    NOT NULL,
  "height"       INT    NOT NULL,
  UNIQUE ("id")
);

CREATE UNIQUE INDEX "asset_transfer_id_idx"
  ON "asset_transfer" ("id");

CREATE DESCENDING INDEX "asset_transfer_asset_id_idx" ON "asset_transfer"("asset_id", "height");

CREATE DESCENDING INDEX "asset_transfer_sender_id_idx" ON "asset_transfer"("sender_id", "height");

CREATE DESCENDING INDEX "asset_transfer_recipient_id_idx" ON "asset_transfer"("recipient_id", "height");

CREATE TABLE "reward_recip_assign" (
  "db_id"         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "account_id"    BIGINT               NOT NULL,
  "prev_recip_id" BIGINT               NOT NULL,
  "recip_id"      BIGINT               NOT NULL,
  "from_height"   INT                  NOT NULL,
  "height"        INT                  NOT NULL,
  "latest"        BOOLEAN DEFAULT TRUE NOT NULL,
  UNIQUE ("account_id", "height")
);

CREATE UNIQUE DESCENDING INDEX "r_r_a_a_i_h_idx" ON "reward_recip_assign"("account_id", "height");

CREATE DESCENDING INDEX "r_r_a_r_i_h_idx" ON "reward_recip_assign"("recip_id", "height");

CREATE TABLE "escrow" (
  "db_id"            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id"               BIGINT               NOT NULL,
  "sender_id"        BIGINT               NOT NULL,
  "recipient_id"     BIGINT               NOT NULL,
  "amount"           BIGINT               NOT NULL,
  "required_signers" INT,
  "deadline"         INT                  NOT NULL,
  "deadline_action"  INT                  NOT NULL,
  "height"           INT                  NOT NULL,
  "latest"           BOOLEAN DEFAULT TRUE NOT NULL,
  UNIQUE ("id", "height")
);

CREATE UNIQUE DESCENDING INDEX "escrow_id_height_idx" ON "escrow"("id", "height");

CREATE DESCENDING INDEX "escrow_sender_id_height_idx" ON "escrow"("sender_id", "height");

CREATE DESCENDING INDEX "escrow_recipient_id_height_idx" ON "escrow"("recipient_id", "height");

CREATE DESCENDING INDEX "escrow_deadline_height_idx" ON "escrow"("deadline", "height");

CREATE TABLE "escrow_decision" (
  "db_id"      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "escrow_id"  BIGINT               NOT NULL,
  "account_id" BIGINT               NOT NULL,
  "decision"   INT                  NOT NULL,
  "height"     INT                  NOT NULL,
  "latest"     BOOLEAN DEFAULT TRUE NOT NULL,
  UNIQUE ("escrow_id", "account_id", "height")
);

CREATE UNIQUE DESCENDING INDEX "e_d_e_i_a_i_h_idx" ON "escrow_decision"("escrow_id", "account_id", "height");

CREATE DESCENDING INDEX "e_d_e_i_h_idx" ON "escrow_decision"("escrow_id", "height");

CREATE DESCENDING INDEX "e_d_a_i_h_idx" ON "escrow_decision"("account_id", "height");

CREATE TABLE "subscription" (
  "db_id"        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id"           BIGINT               NOT NULL,
  "sender_id"    BIGINT               NOT NULL,
  "recipient_id" BIGINT               NOT NULL,
  "amount"       BIGINT               NOT NULL,
  "frequency"    INT                  NOT NULL,
  "time_next"    INT                  NOT NULL,
  "height"       INT                  NOT NULL,
  "latest"       BOOLEAN DEFAULT TRUE NOT NULL,
  UNIQUE ("id", "height")
);

CREATE UNIQUE INDEX "subscription_id_height_idx"
  ON "subscription" ("id", "height");

CREATE DESCENDING INDEX "s_s_i_h_idx" ON "subscription"("sender_id", "height");

CREATE DESCENDING INDEX "s_r_i_h_idx" ON "subscription"("recipient_id", "height");

CREATE TABLE "at" (
  "db_id"              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id"                 BIGINT               NOT NULL,
  "creator_id"         BIGINT               NOT NULL,
  "name"               VARCHAR(30),
  "description"        BLOB SUB_TYPE TEXT,
  "version"            SMALLINT             NOT NULL,
  "csize"              INT                  NOT NULL,
  "dsize"              INT                  NOT NULL,
  "c_user_stack_bytes" INT                  NOT NULL,
  "c_call_stack_bytes" INT                  NOT NULL,
  "creation_height"    INT                  NOT NULL,
  "ap_code"            BLOB                 NOT NULL,
  "height"             INT                  NOT NULL,
  "latest"             BOOLEAN DEFAULT TRUE NOT NULL,
  UNIQUE ("id", "height")
);

CREATE UNIQUE DESCENDING INDEX "at_id_height_idx" ON "at"("id", "height");

CREATE DESCENDING INDEX "at_creator_id_height_idx" ON "at"("creator_id", "height");

CREATE TABLE "at_state" (
  "db_id"                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "at_id"                    BIGINT               NOT NULL,
  "state"                    BLOB                 NOT NULL,
  "prev_height"              INT                  NOT NULL,
  "next_height"              INT                  NOT NULL,
  "sleep_between"            INT                  NOT NULL,
  "prev_balance"             BIGINT               NOT NULL,
  "freeze_when_same_balance" BOOLEAN              NOT NULL,
  "min_activate_amount"      BIGINT               NOT NULL,
  "height"                   INT                  NOT NULL,
  "latest"                   BOOLEAN DEFAULT TRUE NOT NULL,
  UNIQUE ("at_id", "height")
);

CREATE UNIQUE DESCENDING INDEX "at_state_at_id_height_idx" ON "at_state"("at_id", "height");

CREATE DESCENDING INDEX "a_s_i_n_h_h_idx" ON "at_state"("at_id", "next_height", "height");

CREATE TABLE "block" (
  "db_id"                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id"                    BIGINT   NOT NULL,
  "version"               INT      NOT NULL,
  "timestamp"             INT      NOT NULL,
  "previous_block_id"     BIGINT,
  "total_amount"          BIGINT   NOT NULL,
  "total_fee"             BIGINT   NOT NULL,
  "payload_length"        INT      NOT NULL,
  "generator_public_key"  CHAR(32) NOT NULL,
  "previous_block_hash"   CHAR(32),
  "cumulative_difficulty" BLOB     NOT NULL,
  "base_target"           BIGINT   NOT NULL,
  "next_block_id"         BIGINT,
  "height"                INT      NOT NULL,
  "generation_signature"  CHAR(32) NOT NULL,
  "block_signature"       CHAR(64) NOT NULL,
  "payload_hash"          CHAR(32) NOT NULL,
  "generator_id"          BIGINT   NOT NULL,
  "nonce"                 BIGINT   NOT NULL,
  "ats"                   BLOB,
  UNIQUE ("id"),
  UNIQUE ("height"),
  UNIQUE ("timestamp")
);

CREATE UNIQUE INDEX "block_id_idx"
  ON "block" ("id");

CREATE UNIQUE INDEX "block_height_idx"
  ON "block" ("height");

CREATE INDEX "block_generator_id_idx"
  ON "block" ("generator_id");

CREATE UNIQUE DESCENDING INDEX "block_timestamp_idx" ON "block"("timestamp");

ALTER TABLE "transaction"
  ADD CONSTRAINT "constraint_ff" FOREIGN KEY ("block_id") REFERENCES "block" ("id") ON DELETE CASCADE;

ALTER TABLE "block"
  ADD CONSTRAINT "constraint_3c5" FOREIGN KEY ("next_block_id") REFERENCES "block" ("id") ON DELETE SET NULL;

ALTER TABLE "block"
  ADD CONSTRAINT "constraint_3c" FOREIGN KEY ("previous_block_id") REFERENCES "block" ("id") ON DELETE CASCADE;

ALTER TABLE "alias" ALTER COLUMN "alias_name_lower" SET DEFAULT '';

ALTER TABLE "transaction" ALTER COLUMN "r_t_f_hash" TO "referenced_transaction_fullhash";

CREATE INDEX "account_id_latest_idx"
  ON "account" ("id", "latest");